blog/urls.py
from . import views
from django.urls import path

app_name = "blog"
urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('post/<slug:slug>/', views.post_detail, name='post_detail'),
    path('opis_projektu/', views.UsedTech.as_view(), name='used_tech')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('zarzadzanie/', admin.site.urls),
    path('', include('blog.urls'))
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=50)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

blog/views.py
from django.views import generic
from .models import Post
from django.shortcuts import render, get_object_or_404
from .form import CommentForm

class PostList(generic.ListView):
    template_name = 'blog/index.html'
    queryset = Post.objects.filter(status=1).order_by('-created_on')

class UsedTech(generic.TemplateView):
    template_name = 'blog/used_tech.html'
    
def post_detail(request, slug):
    template_name = 'blog/post_detail.html'
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, template_name, {'post': post,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form})

blog/templates/blog/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Blog</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" crossorigin="anonymous" />
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </head>

    {% load static %}
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    
    <body>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
        <nav class="navbar navbar-expand-lg navbar-light fixed-top bg-light" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand fs-5" href="{% url 'blog:home' %}">Mój Blog</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse fs-5" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'blog:used_tech' %}">Opis użytych technologii</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock content %}
        <footer class="py-5 footer-main" id="mainFooter">
            <div class="container text-center">
                <div class="row">
                    <div class="row col-md-12 mx-auto">
                        <div class="col">
                            <p>"Lorem ipsum dolor sit amet"</p>
                        </div>
                        <div class="col">
                            <p>"Lorem ipsum dolor sit amet"</p>
                        </div>
                        <div class="col">
                            <p>"Lorem ipsum dolor sit amet"</p>
                        </div>
                    <div class="row mx-auto col-md-12">
                        <p class="m-0 text-dark text-center text-white">Copyright &copy; Aleksander Wąs</p>
                    </div>        
                </div>
                </div>
            </div>
        </footer>
    </body>
</html>

blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% block content %}

<header class="header">
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto text-center">
                <div class="site-heading">
                    <h1 class="site-heading my-4 mt-3 text-white">Mój Blog</h1>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="bg-image">
    <div class="container">
        <div class="">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8 mt-4 right">
                {% for post in post_list %}
                <div class="card mb-4">
                    <div class="card-body">
                        <h2 class="card-title">{{ post.title }}</h2>
                        <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                        <p class="card-text">{{post.content|slice:":200" }}</p>
                        <a href="{% url 'blog:post_detail' post.slug  %}" class="btn btn-primary">Czytaj dalej &rarr;</a>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% block sidebar %} {% include 'blog/sidebar.html' %} {% endblock sidebar %}
        </div>
    </div>
</div>
{%endblock%}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %} 
{% block content %}

{% load static %}

<link rel="stylesheet" href="{% static 'blog/style.css' %}">

<header class="header">
  <div class="container">
      <div class="row">
          <div class="col-md-12 mx-auto">
              <div class="site-heading">
                  <h3 class="site-heading my-4 mt-3 text-white">Lorem Ipsum: {{ post.title }}</h3>
              </div>
          </div>
      </div>
  </div>
</header>

<div class="container pt-5">
  <div class="row">
    <div class="col-md-8 card mb-4 mt-3">
      <div class="card-body">
        <h1>{% block title %} {{ post.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ post.content | safe }}</p>
      </div>
    </div>
    {% block sidebar %} {% include 'blog/sidebar.html' %} {% endblock sidebar %}
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <h2>{{ comments.count }} Komentarze</h2>

        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.name }}
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
          </p>
          {{ comment.body | linebreaks }}
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Twój komentarz zostanie sprawdzony przez moderatora
        </div>
        {% else %}
        <h3>Zostaw komentarz</h3>
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Wyślij</button>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>

<div class="jumbotron mb-5 text-center" style="padding 70px">
  <a href="{% url 'blog:home' %}" class="btn btn-primary btn-lg">Powrót do listy postów &rarr;</a>
</div> 

{% endblock content %}

blog/templates/blog/sidebar.html
{% block sidebar %}

<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">Technologie</h5>
    <div class="card-body">
        <p class="card-text">"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."
            "There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..."</p>
        <a href="{% url 'blog:used_tech' %}"
           class="btn btn-success">Użyte technologie</a>
    </div>
</div>
</div>

{% endblock sidebar %}

blog/templates/blog/used_tech.html
{% extends "blog/base.html" %}

{% block content %}

<header class="header">
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto text-center">
                <div class="site-heading">
                    <h1 class="site-heading my-4 mt-3 text-white">Opis projektu</h1>
                </div>
            </div>
        </div>
    </div>
</header>


<div class="jumbotron text-center mb-5" style="padding-top: 70px">
    <h2>1. Opis</h2>
</div> 
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <p>Utworzona strona jest blogiem z zarządzalnym CMS-em. Serwis pozwala na dodawanie, edytowanie postów, a także na modernizację komentarzy, które mogą być dodawane przez użytkowników przy pomocy formularza. Strona jest responsywna a także przystępna dla osób niepełnosprawnych.</p>
        <p>Nawigacja opiera się o responsywne menu które znajduje się na każdej z poszczególnych stron.</p>
        <p>W przypadku próby wyświetlenia przez użytkownika serwisu z błędnym odnośnikiem wyświetlany jest szablon z błędem 404. <a href="testbledu404">Przykład</a></p>
      </div>
    </div>
  </div>

  <div class="jumbotron text-center mb-5" style="padding-top: 70px">
    <h2>2. Użyte technologie</h2>
</div>
  <div class="container mb-5">
    <div class="row">
      <div class="col-md-4">
        <h3>Frontend</h3>
        <p>Podstawą jest HTML5<p>
        <p>Na potrzeby projektu wykorzystałem bibliotekę CSS Bootstrap 5 aby strona była responsywna, a także przystępna dla osób z niepełnosprawnościami.</p>
        <p>Dodatkowo używałem również stylów CSS w celu personalizacji niektórych elementów na potrzeby przystępnego wyświetlania strony</p>
      </div>
      <div class="col-md-4">
        <h3>Django</h3>
        <p>Strona bazuje na Frameworku Django który wykorzysałem zarówno po stronie serwera w modelu MVC a także do generacji widoków dla Frontendu. Dodatkowo Framework pozwolił na utworzenie systemu zarządzania treścią (tzw. CMS).</p>
      </div>
      <div class="col-md-4">
        <h3>PostgreSQL</h3>        
        <p>Dodawane posty, komentarze są zapisywane w relacyjnej bazie danych PostgreSQL.</p>
      </div>
      <div class="col-md-6 mt-5">
        <h3>Docker</h3>
        <p>W celu sprawnego oraz szybkiego wdrożenia strony na serwer z publicznym adresem IP użyłem konteneryzacji, gdzie kontenery zostały wydzielone na kontener bazy danych oraz kontener strony internetowej.</p> 
      </div>
    </div>

    <div class="jumbotron text-center mb-5" style="padding-top: 70px">
        <h2>3. Czy wszystkie wymagania dotyczące projektu zostały spełnione?</h2>
    </div> 
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <p>Uważam że jak najbardziej tak ponieważ strona:</p>
            <ul id="check">
                <li>Jest zrealizowana na bazie HTML</li>
                <li>Jest formatowana przy pomocy jezyka CSS oraz biblioteki Bootstrap</li>
                <li>Jest kompatybilna z różnymi nowoczesnymi przeglądarkami</li>
                <li>Jest dostępna dla osób z niepełnosprawnościami (np. tekst alternatywny dodany do obrazków)</li>
                <li>Wykorzystuje co najmniej jedną technologię opisaną na wykładach</li>
                <li>Zawiera przystępny i spójny system nawigacji</li>
                <li>Zawiera stronę poświęconą opisowi projektu</li>
            </ul>

          </div>
        </div>
      </div>

    <div class="jumbotron text-center mb-5" style="padding-top: 70px">
        <h2>4. Materiały dydaktyczne</h2> 
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h4>Materiały, które wykorzystywałem do nauki oraz stworzenia strony:</h4>
                </div>
            </div>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Technologia</th>
                    <th scope="col">Link</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                  <th scope="row">1</th>
                  <td>Django</td>
                  <td><a href="https://www.djangoproject.com/">1. Dokumentacja Django</a><br/><a href="https://djangocentral.com">2. DJangoCentral</a></td>
                </tr>
                <tr>
                  <th scope="row">2</th>
                  <td>Bootstrap</td>
                  <td><a href="https://getbootstrap.com/docs/5.0/getting-started/introduction/">Bootstrap 5</td>
                </tr>
              </tbody>
        </table>
      </div>

    </div>

    <div class="jumbotron mb-5 text-center" style="padding 70px">
        <a href="{% url 'blog:home' %}" class="btn btn-primary btn-lg">Powrót strony głównej &rarr;</a>
    </div> 
      

  {%endblock%}